import Link from "next/link";

export default function Home() {
  return <main className="landing-page">
    <header className="landing-nav"><Link className="brand" href="/"><span className="brand-mark">P</span><span>Pulso</span></Link><nav aria-label="Navegación de presentación"><a href="#funciones">Funciones</a><a href="#proceso">Cómo funciona</a><a href="#resultados">Resultados</a></nav><Link className="button button-dark" href="/admin">Ir al panel <span>→</span></Link></header>
    <section className="hero-section">
      <div className="hero-copy"><span className="hero-pill"><i /> Encuestas claras. Decisiones mejores.</span><h1>Escucha a todos.<br /><em>Entiende lo importante.</em></h1><p>Crea encuestas atractivas, compártelas en segundos y observa cómo cada respuesta se convierte en información útil.</p><div className="hero-actions"><Link className="button button-primary button-large" href="/admin/nueva">Crear una encuesta <span>→</span></Link><a className="button button-ghost button-large" href="#proceso">Ver cómo funciona</a></div><div className="hero-proof"><span><b>✓</b> Sin instalaciones</span><span><b>✓</b> Adaptada a móvil</span><span><b>✓</b> Resultados en vivo</span></div></div>
      <div className="hero-visual" aria-label="Vista previa del panel de Pulso"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><article className="mock-dashboard"><div className="mock-top"><span className="mock-logo">P</span><span>Resumen de resultados</span><i>En vivo</i></div><div className="mock-title"><div><small>Experiencia estudiantil</small><strong>326 respuestas</strong></div><span>+24 hoy</span></div><div className="mock-chart"><div className="chart-grid" /><div className="chart-area" /><div className="chart-line"><i style={{ left: "5%", bottom: "16%" }} /><i style={{ left: "25%", bottom: "33%" }} /><i style={{ left: "46%", bottom: "28%" }} /><i style={{ left: "67%", bottom: "58%" }} /><i style={{ left: "89%", bottom: "76%" }} /></div></div><div className="mock-bars"><span><i style={{ width: "78%" }} /><b>Excelente</b><small>48%</small></span><span><i style={{ width: "56%" }} /><b>Buena</b><small>34%</small></span><span><i style={{ width: "25%" }} /><b>Regular</b><small>15%</small></span></div></article><article className="floating-survey"><span className="floating-count">03 / 06</span><h3>¿Qué tan probable es que nos recomiendes?</h3><div className="floating-scale">{[1, 2, 3, 4, 5].map((number) => <span className={number === 4 ? "selected" : ""} key={number}>{number}</span>)}</div><button>Siguiente →</button></article><div className="floating-response"><span>✓</span><div><strong>Nueva respuesta</strong><small>Ahora mismo</small></div></div></div>
    </section>
    <section className="logo-strip"><span>Una plataforma para</span><strong>educación</strong><i>•</i><strong>equipos</strong><i>•</i><strong>comunidades</strong><i>•</i><strong>investigación</strong></section>
    <section className="feature-section" id="funciones"><div className="section-kicker">Todo lo que necesitas</div><div className="feature-heading"><h2>De la primera pregunta<br />al gráfico final.</h2><p>Pulso reúne creación, distribución y análisis en una experiencia sencilla para quien administra y para quien responde.</p></div><div className="landing-feature-grid"><article className="landing-feature feature-lime"><span className="feature-number">01</span><div className="feature-symbol">＋</div><h3>Construye sin complicaciones</h3><p>Combina preguntas abiertas, opciones, escalas y valoraciones. Reordena y previsualiza antes de publicar.</p><ul><li>8 tipos de pregunta</li><li>Campos obligatorios</li><li>Fechas de apertura y cierre</li></ul></article><article className="landing-feature feature-mint"><span className="feature-number">02</span><div className="feature-symbol">⌁</div><h3>Comparte en segundos</h3><p>Obtén un enlace público y un código QR listo para descargar desde el momento de publicación.</p><ul><li>Enlace único</li><li>QR descargable</li><li>Experiencia móvil</li></ul></article><article className="landing-feature feature-coral" id="resultados"><span className="feature-number">03</span><div className="feature-symbol">↗</div><h3>Entiende cada respuesta</h3><p>Sigue la participación en vivo, cambia de gráfico y exporta los resultados para seguir trabajando.</p><ul><li>Gráficos configurables</li><li>Filtros por período</li><li>CSV, Excel, PDF y PNG</li></ul></article></div></section>
    <section className="process-section" id="proceso"><div className="process-copy"><span className="section-kicker light">Del enlace a la decisión</span><h2>Un flujo simple,<br />de principio a fin.</h2><p>Cada paso está diseñado para reducir fricción y ayudarte a concentrarte en lo que dicen las personas.</p><Link className="button button-primary" href="/admin/nueva">Empezar ahora →</Link></div><ol className="process-list"><li><span>1</span><div><strong>Crea</strong><p>Configura preguntas y ajusta la privacidad.</p></div></li><li><span>2</span><div><strong>Publica</strong><p>Activa la encuesta cuando esté lista.</p></div></li><li><span>3</span><div><strong>Comparte</strong><p>Envía el enlace o muestra el código QR.</p></div></li><li><span>4</span><div><strong>Analiza</strong><p>Observa tendencias y exporta conclusiones.</p></div></li></ol></section>
    <section className="landing-cta"><div><span className="brand-mark brand-mark-large">P</span><h2>La próxima gran decisión<br />empieza con una buena pregunta.</h2><p>Crea tu primera encuesta en Pulso.</p><Link className="button button-primary button-large" href="/admin/nueva">Comenzar ahora <span>→</span></Link></div></section>
    <footer className="landing-footer"><div className="brand"><span className="brand-mark">P</span><span>Pulso</span></div><p>Encuestas claras. Decisiones mejores.</p><span>© 2026 Pulso</span></footer>
  </main>;
}
